logger:
  level: "INFO"

server:
  http:
    host: "127.0.0.1"
    port: "8080"
  grpc:
    port: "49999"

storage:
  type: "memory" # or "sql"

sql:
  dsn: "postgres://calendar_user:calendar@localhost:5432/calendar?sslmode=disable"
