apiVersion: v1
kind: Service
metadata:
  name: {{ include "calendar.fullname" . }}
  labels:
    app: {{ include "calendar.name" . }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "calendar.name" . }}
  ports:
    - name: http
      port: {{ .Values.calendar.ports.http }}
      targetPort: http
    - name: grpc
      port: {{ .Values.calendar.ports.grpc }}
      targetPort: grpc
