apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: ClusterIP
  selector:
    app: {{ include "postgres.name" . }}
  ports:
    - name: pgsql
      port: 5432
      targetPort: pgsql
