apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  type: ClusterIP
  selector:
    app: {{ include "rabbitmq.name" . }}
  ports:
    - name: rmq-mngmt
      port: 15672
      targetPort: rmq-mngmt
    - name: rmq-amqp
      port: 5672
      targetPort: rmq-amqp
